### ISSUE TITLE
Problem in convert variables that the name contains 'ID'

### ISSUE THREAD

**Issue by ehsanasgarian** [asherber/StaTypPocoQueries.PetaPoco#4] opened 2020-12-05 12:43 UTC
..
myObject.Id = 100;
DB.Query<MyClass>(d => d.ObjId == myObject.Id);
must be equivalent to :
DB.Query<MyClass>("WHERE [ObjId] = @0", myObject.Id)  or  DB.Query<MyClass>("WHERE [ObjId] = 100")
but it convert to :
DB.Query<MyClass>("WHERE [ObjId]= Id")
??

**Comment by asherber** [comment] 2020-12-06 21:16
This was a bug in the underlying StaTypPocoQueries library: see https://github.com/d-p-y/statically-typed-poco-queries/issues/7

It was fixed in v1.11.0 of that library last month. This library only requires StaTypPocoQueries >= 1.9, so you'll need to directly add a reference to 1.11.0 in order to get the new behavior. I can reproduce the behavior you see in 1.9, but it works for me in 1.11.

**Comment by ehsanasgarian** [comment] 2020-12-07 04:52
Thanks for addressing this issue so promptly.

**Closed as completed** 2020-12-07 17:46 UTC
